package jframes;

import beanclasses.*;
import dbmanager.DatabaseManager;
import java.awt.*;                  // Toolkit, Dimension
import javax.swing.*;               // JOptionPane    
import java.util.*;                 // Vector    

/** 
 * @author Amjad Jamali
 */
public class BatchFrame extends javax.swing.JFrame {

    public BatchFrame() {
        initComponents();
        Toolkit kit=this.getToolkit();
        Dimension d=kit.getScreenSize();
        setBounds(0,0,d.width, d.height);
        getDepartments();
    }    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batchYears = new javax.swing.JLabel();
        remarks = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        batchYearList = new javax.swing.JList();
        update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        remarksArea = new javax.swing.JTextArea();
        add = new javax.swing.JButton();
        depts = new javax.swing.JLabel();
        departmentComboBox = new javax.swing.JComboBox();
        progs = new javax.swing.JLabel();
        programComboBox = new javax.swing.JComboBox();
        batchIdField = new javax.swing.JTextField();
        batchId = new javax.swing.JLabel();
        batchYearField = new javax.swing.JTextField();
        facName = new javax.swing.JLabel();
        groupComboBox = new javax.swing.JComboBox();
        group = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        batchYears.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        batchYears.setText("Batch Years");
        getContentPane().add(batchYears);
        batchYears.setBounds(1060, 50, 140, 28);

        remarks.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        remarks.setText("Remarks");
        getContentPane().add(remarks);
        remarks.setBounds(330, 330, 120, 28);

        delete.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(810, 700, 150, 60);

        clear.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(650, 700, 150, 60);

        back.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1000, 700, 290, 60);

        batchYearList.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        batchYearList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                batchYearListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(batchYearList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1000, 90, 290, 588);

        update.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(490, 700, 150, 60);

        remarksArea.setColumns(20);
        remarksArea.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        remarksArea.setRows(5);
        jScrollPane2.setViewportView(remarksArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(330, 371, 630, 310);

        add.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(330, 700, 150, 60);

        depts.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        depts.setText("Department");
        getContentPane().add(depts);
        depts.setBounds(330, 90, 169, 28);

        departmentComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        departmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(departmentComboBox);
        departmentComboBox.setBounds(470, 90, 490, 37);

        progs.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        progs.setText("Program");
        getContentPane().add(progs);
        progs.setBounds(330, 150, 169, 28);

        programComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        programComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(programComboBox);
        programComboBox.setBounds(470, 140, 490, 37);

        batchIdField.setEditable(false);
        batchIdField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(batchIdField);
        batchIdField.setBounds(470, 200, 210, 35);

        batchId.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        batchId.setText("Batch Id");
        getContentPane().add(batchId);
        batchId.setBounds(330, 200, 119, 28);

        batchYearField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(batchYearField);
        batchYearField.setBounds(470, 270, 210, 37);

        facName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        facName.setText("Batch Year");
        getContentPane().add(facName);
        facName.setBounds(330, 270, 129, 37);

        groupComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        groupComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BSRS", "ENGINEERING" }));
        groupComboBox.setToolTipText("");
        getContentPane().add(groupComboBox);
        groupComboBox.setBounds(700, 270, 260, 37);

        group.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        group.setText("Group");
        getContentPane().add(group);
        group.setBounds(700, 240, 180, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        BatchBean bean=(BatchBean)this.batchYearList.getSelectedValue();
        if(bean==null)return;
        
        try{
            int rows=DatabaseManager.deleteBatch(bean.getBatchId());
            if(rows>=1){
                 javax.swing.JOptionPane.showMessageDialog(this, rows+" record removed. ");
                 getBatches();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           javax.swing.JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }        
    }//GEN-LAST:event_deleteActionPerformed

    
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        this.batchIdField.setText("");
        this.batchYearField.setText("");
        this.remarksArea.setText("");
    }//GEN-LAST:event_clearActionPerformed

    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        hide();
    }//GEN-LAST:event_backActionPerformed

    
    private void batchYearListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_batchYearListValueChanged
        BatchBean bean = (BatchBean) batchYearList.getSelectedValue();
        if(bean==null)return;
        
        this.batchIdField.setText(""+bean.getBatchId());
        this.batchYearField.setText(""+bean.getBatchYear());
        this.remarksArea.setText(""+bean.getRemarks());
        
        this.groupComboBox.setSelectedItem(bean.getGroupDesc());    
    }//GEN-LAST:event_batchYearListValueChanged

    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        BatchBean bean=(BatchBean)this.batchYearList.getSelectedValue();
        if(bean==null)return;
        
        String batchYear=this.batchYearField.getText();
        String groupDesc=(String)this.groupComboBox.getSelectedItem();
        String remarks=remarksArea.getText();

        if(batchYear.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Program Name TextField is Empty. ");
           return;        
        }        
        try{
        
             int rows=DatabaseManager.updateBatch(bean.getBatchId(),bean.getProgId(), batchYear, groupDesc, remarks);
             if(rows>=1){
                 javax.swing.JOptionPane.showMessageDialog(this, rows+" record modified. ");
                 getBatches();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           javax.swing.JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        ProgramBean bean=(ProgramBean)this.programComboBox.getSelectedItem();
        String batchYear=this.batchYearField.getText();

        String groupDesc=(String)this.groupComboBox.getSelectedItem();
        String remarks=remarksArea.getText();

        if(batchYear.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Program Name TextField is Empty. ");
           return;        
        }        
        try{
        
             int rows=DatabaseManager.addBatch(bean.getProgId(), batchYear, groupDesc, remarks);
             if(rows>=1){
                 javax.swing.JOptionPane.showMessageDialog(this, rows+" record saved. ");
                 getBatches();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           javax.swing.JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }
    }//GEN-LAST:event_addActionPerformed

        private void getDepartments(){
        try{            
            Vector v = DatabaseManager.getDepartments();
            this.departmentComboBox.removeAllItems();
            
            for( int i=0; i<v.size(); i++ )
                this.departmentComboBox.addItem(v.elementAt(i));
            
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"ERROR: "+ex );
        }
    }

    
    private void departmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboBoxActionPerformed
       getPrograms();
    }//GEN-LAST:event_departmentComboBoxActionPerformed
    private void getPrograms(){
        try{
            DepartmentBean bean=(DepartmentBean)this.departmentComboBox.getSelectedItem();
            if(bean==null)return;
            
            Vector v = DatabaseManager.getPrograms(bean.getDeptId());
            this.programComboBox.removeAllItems();
            
            for( int i=0; i<v.size(); i++ )
                this.programComboBox.addItem(v.elementAt(i));
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"ERROR: "+ex );
        }
    }

    
    private void programComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programComboBoxActionPerformed
       getBatches();
    }//GEN-LAST:event_programComboBoxActionPerformed
    private void getBatches(){
        try{
            ProgramBean bean=(ProgramBean)this.programComboBox.getSelectedItem();
            if(bean==null)return;
            
            Vector v = DatabaseManager.getBatches(bean.getProgId());
            this.batchYearList.setListData(v);
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"ERROR: "+ex );
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel batchId;
    private javax.swing.JTextField batchIdField;
    private javax.swing.JTextField batchYearField;
    private javax.swing.JList batchYearList;
    private javax.swing.JLabel batchYears;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox departmentComboBox;
    private javax.swing.JLabel depts;
    private javax.swing.JLabel facName;
    private javax.swing.JLabel group;
    private javax.swing.JComboBox groupComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox programComboBox;
    private javax.swing.JLabel progs;
    private javax.swing.JLabel remarks;
    private javax.swing.JTextArea remarksArea;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
