package jframes;

import beanclasses.*;
import dbmanager.DatabaseManager;
import java.awt.*;                  // Toolkit, Dimension
import javax.swing.*;               // JOptionPane    
import java.util.*;                 // Vector    

/** 
 * @author Shakeel Jamali
 */
public class DepartmentFrame extends javax.swing.JFrame {

    public DepartmentFrame() {
        initComponents();
        Toolkit kit=this.getToolkit();
        Dimension d=kit.getScreenSize();
        setBounds(0,0,d.width, d.height);
           
        getDepartments();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        departments = new javax.swing.JLabel();
        remarks = new javax.swing.JLabel();
        deptId = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        departmentList = new javax.swing.JList();
        update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        remarksArea = new javax.swing.JTextArea();
        add = new javax.swing.JButton();
        deptName = new javax.swing.JLabel();
        deptIdField = new javax.swing.JTextField();
        deptNameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        departments.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        departments.setText("Departments");
        getContentPane().add(departments);
        departments.setBounds(1010, 90, 150, 30);

        remarks.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        remarks.setText("Remarks");
        getContentPane().add(remarks);
        remarks.setBounds(270, 242, 110, 28);

        deptId.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        deptId.setText("Department ID");
        getContentPane().add(deptId);
        deptId.setBounds(270, 120, 174, 28);

        delete.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(760, 590, 150, 60);

        clear.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(600, 590, 150, 60);

        back.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(950, 580, 290, 60);

        departmentList.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        departmentList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                departmentListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(departmentList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(950, 120, 290, 440);

        update.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(440, 590, 150, 60);

        remarksArea.setColumns(20);
        remarksArea.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        remarksArea.setRows(5);
        jScrollPane2.setViewportView(remarksArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(270, 280, 630, 280);

        add.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(280, 590, 150, 60);

        deptName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        deptName.setText("Depatment Name");
        getContentPane().add(deptName);
        deptName.setBounds(270, 180, 210, 28);

        deptIdField.setEditable(false);
        deptIdField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        deptIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptIdFieldActionPerformed(evt);
            }
        });
        getContentPane().add(deptIdField);
        deptIdField.setBounds(480, 120, 200, 38);

        deptNameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        deptNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(deptNameField);
        deptNameField.setBounds(480, 180, 420, 36);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        DepartmentBean bean=(DepartmentBean)this.departmentList.getSelectedValue();
        if(bean==null)return;
        
        try{
            int rows=DatabaseManager.deleteDepartment(bean.getDeptId());
            if(rows>=1){
                 javax.swing.JOptionPane.showMessageDialog(this, rows+" record removed. ");
                 getDepartments();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           javax.swing.JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        deptIdField.setText("");
        deptNameField.setText("");
        remarksArea.setText("");       
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        hide();
    }//GEN-LAST:event_backActionPerformed

    private void departmentListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_departmentListValueChanged
        DepartmentBean bean =(DepartmentBean) departmentList.getSelectedValue();
        if(bean==null)return;
        
        deptIdField.setText(""+bean.getDeptId());
        deptNameField.setText(""+bean.getDeptName());
        remarksArea.setText(""+bean.getRemarks()); 
    }//GEN-LAST:event_departmentListValueChanged

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        DepartmentBean bean=(DepartmentBean)this.departmentList.getSelectedValue();
        if(bean==null)return;
        String deptName=this.deptNameField.getText();
        String remarks=remarksArea.getText();
                
        if(deptName.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Department Name TextField is Empty. ");
           return;        
        }
        
        try{        
             int rows=DatabaseManager.updateDepartment(bean.getDeptId() ,deptName, remarks);
             if(rows>=1){
                 javax.swing.JOptionPane.showMessageDialog(this, rows+" record modified. ");
                 getDepartments();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           javax.swing.JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String deptName=this.deptNameField.getText();
        String remarks=remarksArea.getText();
        
        
        if(deptName.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Department Name TextField is Empty. ");
           return;        
        }        
       
        try{
             int rows=DatabaseManager.addDepartment(deptName, remarks);
             if(rows>=1){
                 javax.swing.JOptionPane.showMessageDialog(this, rows+" record saved. ");
                 getDepartments();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           javax.swing.JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }
                                       

    
    }//GEN-LAST:event_addActionPerformed

    private void getDepartments(){
        try{
            
            Vector v = DatabaseManager.getDepartments();
            departmentList.setListData(v);

        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"ERROR: "+ex );
        }
    }
    

    private void deptNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptNameFieldActionPerformed
        remarksArea.setText("Department Name: "+deptNameField.getText());
    }//GEN-LAST:event_deptNameFieldActionPerformed

    private void deptIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptIdFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JList departmentList;
    private javax.swing.JLabel departments;
    private javax.swing.JLabel deptId;
    private javax.swing.JTextField deptIdField;
    private javax.swing.JLabel deptName;
    private javax.swing.JTextField deptNameField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel remarks;
    private javax.swing.JTextArea remarksArea;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
