package jframes;

import beanclasses.*;
import dbmanager.DatabaseManager;
import java.awt.*;                  // Toolkit, Dimension
import javax.swing.*;               // JOptionPane    
import java.util.*;                 // Vector    

/** 
 * @author Shakeel Jamali
 */
public class ProgramFrame extends javax.swing.JFrame {
    public ProgramFrame() {
        initComponents();
        Toolkit kit=this.getToolkit();
        Dimension d=kit.getScreenSize();
        setBounds(0,0,d.width, d.height);
        getDepartments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        program = new javax.swing.JLabel();
        remarks = new javax.swing.JLabel();
        depts = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        programList = new javax.swing.JList();
        departmentComboBox = new javax.swing.JComboBox();
        update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        remarksArea = new javax.swing.JTextArea();
        add = new javax.swing.JButton();
        progName = new javax.swing.JLabel();
        progId = new javax.swing.JLabel();
        semDuration = new javax.swing.JLabel();
        progIdField = new javax.swing.JTextField();
        progNameField = new javax.swing.JTextField();
        semDurationField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        program.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        program.setText("Programs");
        getContentPane().add(program);
        program.setBounds(1100, 40, 120, 28);

        remarks.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        remarks.setText("Remarks");
        getContentPane().add(remarks);
        remarks.setBounds(350, 280, 130, 28);

        depts.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        depts.setText("Department");
        getContentPane().add(depts);
        depts.setBounds(350, 70, 140, 28);

        delete.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(830, 660, 150, 60);

        clear.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(670, 660, 150, 60);

        back.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1010, 660, 300, 60);

        programList.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        programList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                programListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(programList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1010, 70, 300, 564);

        departmentComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        departmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(departmentComboBox);
        departmentComboBox.setBounds(570, 70, 400, 37);

        update.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(510, 660, 150, 60);

        remarksArea.setColumns(20);
        remarksArea.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        remarksArea.setRows(5);
        jScrollPane2.setViewportView(remarksArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(350, 320, 630, 320);

        add.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(350, 660, 150, 60);

        progName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        progName.setText("Program Name");
        getContentPane().add(progName);
        progName.setBounds(350, 180, 190, 28);

        progId.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        progId.setText("Program ID");
        getContentPane().add(progId);
        progId.setBounds(350, 130, 129, 28);

        semDuration.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        semDuration.setText("Semester Duration");
        getContentPane().add(semDuration);
        semDuration.setBounds(350, 230, 220, 28);

        progIdField.setEditable(false);
        progIdField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(progIdField);
        progIdField.setBounds(570, 120, 200, 36);

        progNameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(progNameField);
        progNameField.setBounds(570, 180, 400, 37);

        semDurationField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(semDurationField);
        semDurationField.setBounds(570, 230, 400, 37);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        ProgramBean bean=(ProgramBean)this.programList.getSelectedValue();
        if(bean==null)return;
        
        try{
            int rows=DatabaseManager.deleteProgram(bean.getProgId());
            if(rows>=1){
                 javax.swing.JOptionPane.showMessageDialog(this, rows+" record removed. ");
                 getPrograms();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           javax.swing.JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        this.progIdField.setText("");
        this.progNameField.setText("");
        this.semDurationField.setText("");
        this.remarksArea.setText("");   
    }//GEN-LAST:event_clearActionPerformed

    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        hide();
    }//GEN-LAST:event_backActionPerformed

    
    private void programListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_programListValueChanged
        ProgramBean bean = (ProgramBean) programList.getSelectedValue();
        if(bean==null)return;
        
        this.progIdField.setText(""+bean.getProgId());
        this.progNameField.setText(""+bean.getProgName());
        this.semDurationField.setText(""+bean.getSemDuration());
        this.remarksArea.setText(""+bean.getRemarks());   
    }//GEN-LAST:event_programListValueChanged


    private void departmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboBoxActionPerformed
       getPrograms();
    }//GEN-LAST:event_departmentComboBoxActionPerformed
    private void getPrograms(){
        try{
            DepartmentBean bean=(DepartmentBean)this.departmentComboBox.getSelectedItem();
            if(bean==null)return;        
            Vector v = DatabaseManager.getPrograms(bean.getDeptId());
            this.programList.setListData(v);

        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"ERROR: "+ex );
        }
    }

    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        ProgramBean bean=(ProgramBean)this.programList.getSelectedValue();
        if(bean==null)return;
        
        String progName=this.progNameField.getText();
        String semDuration=this.semDurationField.getText();
        String remarks=remarksArea.getText();
       
        if(progName.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Program Name TextField is Empty. ");
           return;        
        }
        if(semDuration.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Semester Duration TextField is Empty. ");
           return;        
        }
        
        try{
             int rows=DatabaseManager.updateProgram(bean.getProgId(), bean.getDeptId(), progName, semDuration, remarks);
             if(rows>=1){
                 javax.swing.JOptionPane.showMessageDialog(this, rows+" record modified. ");
                 getDepartments();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           javax.swing.JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        DepartmentBean bean=(DepartmentBean)this.departmentComboBox.getSelectedItem();
        String progName=this.progNameField.getText();
        String semDuration=this.semDurationField.getText();
        String remarks=remarksArea.getText();
        
        if(progName.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Program Name TextField is Empty. ");
           return;        
        }
        else if(semDuration.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Semeter Duration TextField is Empty. ");
           return;        
        }
        
        try{
        
             int rows=DatabaseManager.addProgram(bean.getDeptId(),progName, semDuration, remarks);
             if(rows>=1){
                 javax.swing.JOptionPane.showMessageDialog(this, rows+" record saved. ");
                 getPrograms();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           javax.swing.JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }
    }//GEN-LAST:event_addActionPerformed

        private void getDepartments(){
        try{
            
            Vector v = DatabaseManager.getDepartments();
            this.departmentComboBox.removeAllItems();
            
            for( int i=0; i<v.size(); i++ )
                this.departmentComboBox.addItem(v.elementAt(i));
            
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"ERROR: "+ex );
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox departmentComboBox;
    private javax.swing.JLabel depts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel progId;
    private javax.swing.JTextField progIdField;
    private javax.swing.JLabel progName;
    private javax.swing.JTextField progNameField;
    private javax.swing.JLabel program;
    private javax.swing.JList programList;
    private javax.swing.JLabel remarks;
    private javax.swing.JTextArea remarksArea;
    private javax.swing.JLabel semDuration;
    private javax.swing.JTextField semDurationField;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
