package jframes;

import java.awt.*;

/**
 * @author Shakeel Jamali
 */
public class ProjectMainFrame extends javax.swing.JFrame {

DepartmentFrame departmentFrame = new DepartmentFrame(); 
ProgramFrame programFrame = new ProgramFrame();    
BatchFrame batchFrame = new BatchFrame();    
StudentFrame studentFrame = new StudentFrame();    
BooksFrame booksFrame = new BooksFrame();    
BookIssueFrame bookIssueFrame = new BookIssueFrame();    
BookTypeFrame bookTypeFrame = new BookTypeFrame();    
    
    
    /**
     * Creates new form DepartmentFrame
     */
    public ProjectMainFrame() {
        initComponents();
        Toolkit kit=this.getToolkit();
        Dimension d=kit.getScreenSize();
        this.setSize(d);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        faculties7 = new javax.swing.JLabel();
        faculties8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        department = new javax.swing.JMenuItem();
        program = new javax.swing.JMenuItem();
        batch = new javax.swing.JMenuItem();
        student = new javax.swing.JMenuItem();
        books = new javax.swing.JMenuItem();
        bookType = new javax.swing.JMenuItem();
        bookIssued = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        faculties7.setFont(new java.awt.Font("Candles", 0, 48)); // NOI18N
        faculties7.setText("Libarary Managment");
        getContentPane().add(faculties7);
        faculties7.setBounds(520, 660, 540, 60);

        faculties8.setFont(new java.awt.Font("Candles", 0, 48)); // NOI18N
        faculties8.setText("MUET SZAB Campus Khairpur Mir's");
        getContentPane().add(faculties8);
        faculties8.setBounds(380, 710, 790, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframes/MUET_LOGO.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 20, 750, 640);

        file.setBackground(new java.awt.Color(255, 255, 204));
        file.setBorder(new javax.swing.border.MatteBorder(null));
        file.setText("Setup");
        file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileMouseClicked(evt);
            }
        });

        department.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        department.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        department.setText("Department");
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        file.add(department);

        program.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        program.setBackground(new java.awt.Color(255, 255, 204));
        program.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        program.setText("Program");
        program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programActionPerformed(evt);
            }
        });
        file.add(program);

        batch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        batch.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        batch.setText("Batch");
        batch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchActionPerformed(evt);
            }
        });
        file.add(batch);

        student.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        student.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        student.setText("Student");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        file.add(student);

        books.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        books.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        books.setText("Books");
        books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksActionPerformed(evt);
            }
        });
        file.add(books);

        bookType.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        bookType.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        bookType.setText("BookType");
        bookType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTypeActionPerformed(evt);
            }
        });
        file.add(bookType);

        bookIssued.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        bookIssued.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        bookIssued.setText("BookIssued");
        bookIssued.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIssuedActionPerformed(evt);
            }
        });
        file.add(bookIssued);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        exit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        file.add(exit);

        jMenuBar1.add(file);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMouseClicked
    }//GEN-LAST:event_fileMouseClicked

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        departmentFrame.show();
    }//GEN-LAST:event_departmentActionPerformed

    private void programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programActionPerformed
        programFrame.show();
    }//GEN-LAST:event_programActionPerformed

    private void batchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchActionPerformed
        batchFrame.show();
    }//GEN-LAST:event_batchActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        studentFrame.show();         
    }//GEN-LAST:event_studentActionPerformed

    private void booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksActionPerformed
        booksFrame.show();         
    }//GEN-LAST:event_booksActionPerformed

    private void bookTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTypeActionPerformed
        bookTypeFrame.show();         
    }//GEN-LAST:event_bookTypeActionPerformed

    private void bookIssuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIssuedActionPerformed
        bookIssueFrame.show();         
    }//GEN-LAST:event_bookIssuedActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectMainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem batch;
    private javax.swing.JMenuItem bookIssued;
    private javax.swing.JMenuItem bookType;
    private javax.swing.JMenuItem books;
    private javax.swing.JMenuItem department;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel faculties7;
    private javax.swing.JLabel faculties8;
    private javax.swing.JMenu file;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem program;
    private javax.swing.JMenuItem student;
    // End of variables declaration//GEN-END:variables

}