package jframes;

import beanclasses.*;
import dbmanager.DatabaseManager;
import java.awt.*;                  // Toolkit, Dimension
import javax.swing.*;               // JOptionPane    
import java.util.*;                 // Vector    

/** 
 * @author Amjad Jamali
 */
public class StudentFrame extends javax.swing.JFrame {

    public StudentFrame() {
        initComponents();
        Toolkit kit=this.getToolkit();
        Dimension d=kit.getScreenSize();
        setBounds(0,0,d.width, d.height);
        getDepartments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batchYears = new javax.swing.JLabel();
        remarks = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentNameList = new javax.swing.JList();
        update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        remarksArea = new javax.swing.JTextArea();
        add = new javax.swing.JButton();
        depts = new javax.swing.JLabel();
        departmentComboBox = new javax.swing.JComboBox();
        progs = new javax.swing.JLabel();
        programComboBox = new javax.swing.JComboBox();
        studentIdField = new javax.swing.JTextField();
        batchYear = new javax.swing.JLabel();
        studentNameField = new javax.swing.JTextField();
        facName = new javax.swing.JLabel();
        group = new javax.swing.JLabel();
        batchYearComboBox = new javax.swing.JComboBox();
        groupField = new javax.swing.JTextField();
        stdName = new javax.swing.JLabel();
        fName = new javax.swing.JLabel();
        fNameField = new javax.swing.JTextField();
        rollNo = new javax.swing.JLabel();
        rollNoField = new javax.swing.JTextField();
        surname = new javax.swing.JLabel();
        surnameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        batchYears.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        batchYears.setText("Students");
        getContentPane().add(batchYears);
        batchYears.setBounds(1080, 10, 110, 28);

        remarks.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        remarks.setText("Remarks");
        getContentPane().add(remarks);
        remarks.setBounds(320, 430, 120, 28);

        delete.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(800, 680, 150, 60);

        clear.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(640, 680, 150, 60);

        back.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1000, 680, 290, 60);

        studentNameList.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        studentNameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                studentNameListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(studentNameList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1000, 40, 290, 610);

        update.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(480, 680, 150, 60);

        remarksArea.setColumns(20);
        remarksArea.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        remarksArea.setRows(5);
        jScrollPane2.setViewportView(remarksArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(320, 470, 630, 180);

        add.setFont(new java.awt.Font("Gazzarelli", 1, 24)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(320, 680, 150, 60);

        depts.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        depts.setText("Department");
        getContentPane().add(depts);
        depts.setBounds(320, 60, 140, 28);

        departmentComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        departmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(departmentComboBox);
        departmentComboBox.setBounds(490, 50, 450, 37);

        progs.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        progs.setText("Program");
        getContentPane().add(progs);
        progs.setBounds(320, 110, 100, 28);

        programComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        programComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(programComboBox);
        programComboBox.setBounds(490, 100, 450, 37);

        studentIdField.setEditable(false);
        studentIdField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(studentIdField);
        studentIdField.setBounds(490, 190, 220, 35);

        batchYear.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        batchYear.setText("Batch Year");
        getContentPane().add(batchYear);
        batchYear.setBounds(320, 150, 133, 28);

        studentNameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(studentNameField);
        studentNameField.setBounds(490, 240, 450, 37);

        facName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        facName.setText("Student ID");
        getContentPane().add(facName);
        facName.setBounds(320, 190, 129, 30);

        group.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        group.setText("Group");
        getContentPane().add(group);
        group.setBounds(740, 160, 80, 22);

        batchYearComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        batchYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchYearComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(batchYearComboBox);
        batchYearComboBox.setBounds(490, 150, 220, 37);

        groupField.setEditable(false);
        groupField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(groupField);
        groupField.setBounds(740, 190, 190, 35);

        stdName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        stdName.setText("Studunt Name");
        getContentPane().add(stdName);
        stdName.setBounds(320, 240, 163, 30);

        fName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        fName.setText("Father Name");
        getContentPane().add(fName);
        fName.setBounds(320, 290, 160, 30);

        fNameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(fNameField);
        fNameField.setBounds(490, 290, 450, 37);

        rollNo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        rollNo.setText("Roll No:");
        getContentPane().add(rollNo);
        rollNo.setBounds(320, 390, 92, 30);

        rollNoField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(rollNoField);
        rollNoField.setBounds(490, 390, 220, 37);

        surname.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        surname.setText("Surname");
        getContentPane().add(surname);
        surname.setBounds(320, 340, 102, 30);

        surnameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(surnameField);
        surnameField.setBounds(490, 340, 450, 37);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        StudentBean bean=(StudentBean)this.studentNameList.getSelectedValue();
        if(bean==null)return;
        
        try{
            int rows=DatabaseManager.deleteStudent(bean.getStdId());
            if(rows>=1){
                 JOptionPane.showMessageDialog(this, rows+" record removed. ");
                 getStudents();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        this.studentIdField.setText("");
        this.studentNameField.setText("");
        this.fNameField.setText("");
        this.surnameField.setText("");
        this.rollNoField.setText(""); 
        this.remarksArea.setText(""); 
    }//GEN-LAST:event_clearActionPerformed

    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        hide();
    }//GEN-LAST:event_backActionPerformed

    
    private void studentNameListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_studentNameListValueChanged
        StudentBean bean = (StudentBean) studentNameList.getSelectedValue();
        if(bean==null)return;
       
        this.studentIdField.setText(""+bean.getStdId());
        this.studentNameField.setText(""+bean.getStdName());
        this.fNameField.setText(""+bean.getFName());
        this.surnameField.setText(""+bean.getSurname());
        this.rollNoField.setText(""+bean.getRollNo()); 
        this.remarksArea.setText(""+bean.getRemarks()); 
    }//GEN-LAST:event_studentNameListValueChanged

    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        StudentBean bean=(StudentBean)this.studentNameList.getSelectedValue();
        String stdName=this.studentNameField.getText();
        String fName=this.fNameField.getText();
        String surname=this.surnameField.getText();
        String rollNo=this.rollNoField.getText();
        String remarks=remarksArea.getText();

        if(stdName.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Student Name TextField is Empty. ");
           return;        
        }
        if(fName.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Father Name TextField is Empty. ");
           return;        
        }
        if(surname.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Surname TextField is Empty. ");
           return;        
        }
        if(rollNo.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Roll# TextField is Empty. ");
           return;        
        }
        try{
             int rows=DatabaseManager.updateStudent(bean.getStdId(),bean.getBatchId(), stdName, fName,surname, rollNo, remarks);
             if(rows>=1){
                 JOptionPane.showMessageDialog(this, rows+" record modified. ");
                 getStudents();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        BatchBean bean=(BatchBean)this.batchYearComboBox.getSelectedItem();
        String stdName=this.studentNameField.getText();
        String fName=this.fNameField.getText();
        String surname=this.surnameField.getText();
        String rollNo=this.rollNoField.getText();
        String remarks=remarksArea.getText();

        if(stdName.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Student Name TextField is Empty. ");
           return;        
        }
        if(fName.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Father Name TextField is Empty. ");
           return;        
        }
        if(surname.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Surname TextField is Empty. ");
           return;        
        }
        if(rollNo.trim().equals("")){
           JOptionPane.showMessageDialog(this, "Roll# TextField is Empty. ");
           return;        
        }
        try{
             int rows=DatabaseManager.addStudent(bean.getBatchId(), stdName, fName,surname, rollNo, remarks);
             if(rows>=1){
                 JOptionPane.showMessageDialog(this, rows+" record saved. ");
                 getStudents();
                 clearActionPerformed(evt);                                      
             }
        }catch(Exception ee){
           ee.printStackTrace();
           JOptionPane.showMessageDialog(this,"Error: "+ee.getMessage());
        }
    }//GEN-LAST:event_addActionPerformed

    
    private void departmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboBoxActionPerformed
        getPrograms();
    }//GEN-LAST:event_departmentComboBoxActionPerformed
    private void getPrograms(){
        try{
            DepartmentBean bean=(DepartmentBean)this.departmentComboBox.getSelectedItem();
            if(bean==null)return;
            Vector v = DatabaseManager.getPrograms(bean.getDeptId());
            this.programComboBox.removeAllItems();
            
            for( int i=0; i<v.size(); i++ )
                this.programComboBox.addItem(v.elementAt(i));
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"ERROR: "+ex );
        }
    }

    
    private void programComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programComboBoxActionPerformed
        getBatches();
    }//GEN-LAST:event_programComboBoxActionPerformed
    private void getBatches(){
        try{
            ProgramBean bean=(ProgramBean)this.programComboBox.getSelectedItem();
            if(bean==null)return;
            Vector v = DatabaseManager.getBatches(bean.getProgId());
            this.batchYearComboBox.removeAllItems();

            for( int i=0; i<v.size(); i++ )
                this.batchYearComboBox.addItem(v.elementAt(i));
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"ERROR: "+ex );
        }
    }


    private void batchYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchYearComboBoxActionPerformed
        getStudents();
    }//GEN-LAST:event_batchYearComboBoxActionPerformed
    private void getStudents(){
        try{
            BatchBean bean=(BatchBean)this.batchYearComboBox.getSelectedItem();
            if(bean==null)return;

            this.groupField.setText(bean.getGroupDesc());
            
            
            Vector v = DatabaseManager.getStudents(bean.getBatchId());
            this.studentNameList.setListData(v);
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"ERROR: "+ex );
        }
    }
    
        private void getDepartments(){
        try{
            
            Vector v = DatabaseManager.getDepartments();
            this.departmentComboBox.removeAllItems();
            
            for( int i=0; i<v.size(); i++ )
                this.departmentComboBox.addItem(v.elementAt(i));
            
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"ERROR: "+ex );
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel batchYear;
    private javax.swing.JComboBox batchYearComboBox;
    private javax.swing.JLabel batchYears;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox departmentComboBox;
    private javax.swing.JLabel depts;
    private javax.swing.JLabel fName;
    private javax.swing.JTextField fNameField;
    private javax.swing.JLabel facName;
    private javax.swing.JLabel group;
    private javax.swing.JTextField groupField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox programComboBox;
    private javax.swing.JLabel progs;
    private javax.swing.JLabel remarks;
    private javax.swing.JTextArea remarksArea;
    private javax.swing.JLabel rollNo;
    private javax.swing.JTextField rollNoField;
    private javax.swing.JLabel stdName;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JTextField studentNameField;
    private javax.swing.JList studentNameList;
    private javax.swing.JLabel surname;
    private javax.swing.JTextField surnameField;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
